### ISSUE TITLE
Had to make a bat file to run it.

### ISSUE THREAD

**Issue by marufmoinuddin** [sanjib-sen/buX_Calendar#2]
The pyw file didn't opened by double click. At least not in my laptops. So I had to create a custom .bat file to run it.
[BuX_Cal.zip](https://github.com/sanjib-sen/buX_Calendar/files/5299955/BuX_Cal.zip)

**Comment by sanjib-sen** [comment]
Does it work now? I mean using the bat file?
I guess it is because It needs some  external modules  like beautifulsoup4. 

I am testing using the bat file, I will merge it if it works. 
Thank you so much for testing, brother.

**Comment by marufmoinuddin** [comment]
yes with bat file it works. also please put the modules to install in your bat file. beautifulsoup4 was installed previously in my python. but it originally doesn't come with python.

**Comment by sanjib-sen** [comment]
I will do it.  I am thinking about making it easier to Users to actually use this software. Previously pyinstaller worked fine for including required modules to a single executable file. But, it doesn't work now with Python 3.8. I have been trying to downgrade but no luck. I will try again though.
And brother, if you know any other way to make it executable and user friendly please let me know.

**Comment by sanjib-sen** [comment]
> yes with bat file it works. also please put the modules to install in your bat file. beautifulsoup4 was installed previously in my python. but it originally doesn't come with python.

Bhaiya, Can you check the new release? Just running the exe file should work now. Finally managed to make a proper executable using cxxfreeze. Thanks for the support.

**Comment by marufmoinuddin** [comment]
sure

> > yes with bat file it works. also please put the modules to install in your bat file. beautifulsoup4 was installed previously in my python. but it originally doesn't come with python.
> 
> Bhaiya, Can you check the new release? Just running the exe file should work now. Finally managed to make a proper executable using cxxfreeze. Thanks for the support.

**Comment by sanjib-sen** [comment]
The app can now work without creating any bat file. Even Python doesn't require now. 
Tested in various devices by some users.
Anyway, Thanks for your feedback brother. I am closing this issue.
