### ISSUE TITLE
Does Anybody Know a better alternative to pyinstaller? Or some way to make an executable file out of pyw?

### ISSUE THREAD

**Issue by sanjib-sen** [sanjib-sen/buX_Calendar#3]
I have been trying to convert the pyw file to an executable binary or exe file, But It seems like [ pyinstaller] (https://pypi.org/project/pyinstaller/) doesn't work.
It is because pyinstaller doesn't support Python 3.8 and I couldn't manage to downgrade it. On the other hand, py2exe finally works on python 3.x.x but still outdated, didn't work for my file.

So, I am looking for a way to make it easier for users to use the software. Please let me know your thoughts.

**Comment by shabab477** [comment]
Have you looked into [cxfreexe](https://cx-freeze.readthedocs.io/en/latest/)? 

Also, you may want to think about dockerizing the business logic and host it over heroku. The front end part can be just a flutter or react native or javafx project. Probably too much complicated for now but putting an effort now should make the deployment much smoother.

**Comment by sanjib-sen** [comment]
> Have you looked into [cxfreexe](https://cx-freeze.readthedocs.io/en/latest/)?
> 
> Also, you may want to think about dockerizing the business logic and host it over heroku. The front end part can be just a flutter or react native or javafx project. Probably too much complicated for now but putting an effort now should make the deployment much smoother.


I do not know how to thank you bhaia, I used the cxfreexe module and it worked perfectly. Even it can build a msi file. Thank You So much,

**Comment by shabab477** [comment]
Cool! You can close this issue and start working on some sort of CD pipeline with cxfreeze. Also my name in release note should be Shabab not Shadab, anyways NVM :smiley:

**Comment by sanjib-sen** [comment]
Sorry for the mistake bro. Edited it.
Thank you for the feedback.
